import { Caprasimo, Boogaloo, Poppins } from 'next/font/google'
import './globals.css'

const caprasimoFont = Caprasimo({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-caprasimo',
})

const boogalooFont = Boogaloo({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-boogaloo',
})

const poppinsRegular = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poppinsRegular',
})

const poppinsLightItalic = Poppins({
  weight: '300',
  style: 'italic',
  subsets: ['latin'],
  variable: '--font-poppinsLightItalic',
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${caprasimoFont.variable} ${boogalooFont.variable} ${poppinsLightItalic.variable} ${poppinsRegular.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}

